apiRules:
- include:
    uidRegex: ^nickmaltbie\.RecolorShaderUnity
    type: Namespace
- include:
    uidRegex: ^nickmaltbie\.RecolorShaderUnity\.*
    type: Namespace
- exclude:
    uidRegex: .*
    type: Namespace